[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NODE_NAMESPACE = "true"

[functions]
  directory = ".next/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
