[build]
  command = "npm run build"
  publish = "docs"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  
# Static site configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
