[build]
  command = "npm run build"
  publish = "docs"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  
# Required for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Disable the Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
  enabled = false
