[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_USE_NODE_NAMESPACE = "true"

[functions]
  directory = ".next/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    publish = "out"
