[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  
# Required for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
